version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./Server:/src
    environment:
      - REDIS_URL=${REDIS_URL}

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    container_name: worker
    depends_on:
      - redis
    volumes:
      - ./Worker:/src
    environment:
      - REDIS_URL=${REDIS_URL}

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/src
    environment:
      - VITE_REACT_APP_SERVER_URL=${VITE_REACT_APP_SERVER_URL}

volumes:
  redis-data:
