version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
      target: prod # Use 'prod' for production or 'dev' for development
    container_name: server
    depends_on:
      - redis
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./Server/src:/src/src
    env_file:
      - ./Server/.env

  worker:
    build:
      context: ./Worker
      dockerfile: Dockerfile
    container_name: worker
    depends_on:
      - redis
    volumes:
      - ./Worker/src:/src/src
    env_file:
      - ./Worker/.env

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/src
    env_file:
      - ./Client/.env

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
