version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  server:
    image: "disha968/server:latest"
    container_name: server
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=${REDIS_URL}

  worker:
    image: "disha968/worker:latest"
    container_name: worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}

  # client:
  #   image: "disha968/client:latest"
  #   container_name: client
  #   depends_on:
  #     - server
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - VITE_REACT_APP_SERVER_URL=${VITE_REACT_APP_SERVER_URL}
