name: Build & Deploy to Docker Hub

on:
  push:
    branches:
      - cicd-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for Server
        uses: docker/build-push-action@v2
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server:latest # Replace with your Docker Hub username and repository
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}

      - name: Build and Push Docker image for Worker
        uses: docker/build-push-action@v2
        with:
          context: ./Worker
          file: ./Worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/worker:latest # Replace with your Docker Hub username and repository
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}

      - name: Build and Push Docker image for Client
        uses: docker/build-push-action@v2
        with:
          context: ./Client
          file: ./Client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client:latest # Replace with your Docker Hub username and repository
        env:
          VITE_REACT_APP_SERVER_URL: ${{ secrets.VITE_REACT_APP_SERVER_URL }}

      - name: Deploy and Start Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/docker
            sudo chown ubuntu:ubuntu /home/ubuntu/docker
            echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
            chmod 700 key.pem
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.EC2_SSH_HOST }} >> ~/.ssh/known_hosts
            scp -i key.pem docker-compose-prod.yml ${{ secrets.EC2_SSH_USERNAME }}@${{ secrets.EC2_SSH_HOST }}:/home/ubuntu/docker/
            cd /home/ubuntu/docker
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" > .env
            echo "VITE_REACT_APP_SERVER_URL=${{ secrets.VITE_REACT_APP_SERVER_URL }}" >> .env
            sudo docker compose --env-file .env -f docker-compose-prod.yml up -d
