name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - cd-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image for Server 
      uses: docker/build-push-action@v2
      with:
        context: ./Server
        file: ./Server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/server:latest  # Replace with your Docker Hub username and repository
      env:
        REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Build and Push Docker image for Worker 
      uses: docker/build-push-action@v2
      with:
          context: ./Worker
          file: ./Worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/worker:latest  # Replace with your Docker Hub username and repository
      env:
          REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Build and Push Docker image for Client 
      uses: docker/build-push-action@v2
      with:
          context: ./Client
          file: ./Client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client:latest  # Replace with your Docker Hub username and repository
      env:
          VITE_REACT_APP_SERVER_URL: ${{ secrets.VITE_REACT_APP_SERVER_URL }}      
        
         
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
            host: ${{ secrets.EC2_SSH_HOST }}
            username: ${{ secrets.EC2_SSH_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                sudo mkdir -p docker
          
    - name: Create SSH key file
      run: echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
              
    - name: Set permissions for SSH key
      run: chmod 700 key.pem            

    - name: Transfer Docker Compose file to EC2
      run: scp -i key.pem docker-compose-prod.yml ${{ secrets.EC2_SSH_USERNAME }}@${{ secrets.EC2_SSH_HOST }}:/
    
    